package test.ipo.task1.service;import java.io.IOException;import org.testng.Assert;import org.testng.annotations.DataProvider;import org.testng.annotations.Test;import by.ipo.task1.service.SumOfSquares;public class SumOfSquaresTest {		SumOfSquares sos = SumOfSquares.getInstance();		@DataProvider(name = "numbersData")	public Object[][] setData() {		return new Object[][] { 								{20, 2870}, {100, 338350}							  };		}		@DataProvider(name = "numbersWrongData")	public Object[][] setWrongData() {		return new Object[][] { 								{-100, new IOException()},								{0, new IOException()},							  };		}		@Test(description = "Проверка квадратов первых ста чисел", 		  dataProvider = "numbersData")	public void getSumTest(int quantity, int expectedAnswer) 			throws IOException {		Assert.assertEquals(sos.getSum(quantity), expectedAnswer);	}		@Test(description = "Проверка квадратов первых ста чисел", 		  dataProvider = "numbersWrongData",		  expectedExceptions = IOException.class)	public void getSumTestWrong(int quantity, IOException expectedAnswer) 			throws IOException {		Assert.assertEquals(sos.getSum(quantity), expectedAnswer);	}}